export const completeScenario = {
  schemaVersion: 1,
  id: "four-orders-two-drivers",
  title: "Four orders and two drivers",
  description: "Exercises adaptive bundling with deterministic providers.",
  seed: 42017,
  tags: ["dispatch", "routing", "ui"],
  capabilities: ["browser", "routing-simulator"],
  environment: "local",
  tenant: { id: "testlab_alpha" },
  clock: { start: "2026-08-01T18:00:00+02:00" },
  stores: [{ id: "store-a", prepQueueMinutes: 6 }],
  actors: [
    { id: "customer-1", kind: "customer", profile: "instant" },
    { id: "customer-2", kind: "customer", profile: "multi-item" },
    { id: "driver-1", kind: "driver", profile: "bike-small" },
    { id: "driver-2", kind: "driver", profile: "car-large" },
    { id: "kitchen-1", kind: "kitchen", profile: "normal" },
    { id: "system-1", kind: "system", profile: "canonical" },
  ],
  vehicles: [{ id: "bike-1", kind: "bike", capacityOrders: 2 }, { id: "car-1", kind: "car", capacityOrders: 4 }],
  drivers: [
    { actor: "driver-1", vehicle: "bike-1", state: "idle", start: { lat: 52.52, lng: 13.4 }, gpsFixture: "near-store" },
    { actor: "driver-2", vehicle: "car-1", state: "idle", start: { lat: 52.5, lng: 13.38 }, gpsFixture: "west-route" },
  ],
  orders: [
    { id: "order-1", customer: "customer-1", store: "store-a", items: [{ id: "item-1", quantity: 1, required: true }], createdAtOffsetSeconds: 0, prepMinutes: 8, deadlineMinutes: 42, payment: "confirmed" },
    { id: "order-2", customer: "customer-2", store: "store-a", items: [{ id: "item-2", quantity: 2, required: true }], createdAtOffsetSeconds: 15, prepMinutes: 9, deadlineMinutes: 50, payment: "confirmed" },
  ],
  fixtures: { routing: "evening-route", traffic: "evening-traffic", push: "reliable-push", network: "reliable-network" },
  steps: [{ actor: "customer-1", action: "place-order", atSeconds: 0 }, { actor: "system-1", action: "run-dispatch", atSeconds: 20 }],
  chaos: [{ atSeconds: 30, fault: "network-drop", target: "driver-1" }],
  expect: { uiStates: ["order-visible"], invariants: ["no-duplicate-assignment", "all-orders-accounted"], selectedDriver: "driver-2", bundleSize: 2, stopOrder: ["pickup-order-1", "dropoff-order-1", "dropoff-order-2"], optimizationTolerance: 0 },
  cleanup: { scope: "run-only", verifyZeroRows: true },
} as const
