'use client';
import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
export function ApplicantAssessment({ token }: { token: string }) {
  const [data, setData] = useState<any>(); const [answers, setAnswers] = useState<Record<string, string[]>>({}); const [error, setError] = useState(''); const [pending, setPending] = useState(false);
  useEffect(() => { fetch(`/api/application-assessments/public/${token}`).then(async (r) => { const d = await r.json(); if (!r.ok) setError(d.error); else setData(d); }); }, [token]);
  async function submit() { setPending(true); setError(''); const response = await fetch(`/api/application-assessments/public/${token}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ answers }) }); const result = await response.json(); setPending(false); if (!response.ok) return setError(result.error); setData({ ...data, result: result.result, questions: [] }); }
  if (error && !data) return <Card className="mx-auto max-w-xl"><CardContent className="p-8 text-center"><h1 className="font-semibold">Test nicht verfügbar</h1><p className="mt-2 text-sm text-muted-foreground">{error}</p></CardContent></Card>;
  if (!data) return <p className="text-center text-sm text-muted-foreground">Test wird geladen…</p>;
  if (data.result) return <Card className="mx-auto max-w-xl"><CardContent className="p-8 text-center"><h1 className="text-2xl font-bold">Vielen Dank!</h1><p className="mt-3">{data.result.outcome_message ?? 'Deine Antworten wurden sicher übermittelt.'}</p></CardContent></Card>;
  return <div className="mx-auto max-w-2xl space-y-4"><header className="mb-6"><p className="text-sm text-muted-foreground">Hallo {data.session.candidate?.vorname}</p><h1 className="text-2xl font-bold">{data.session.template?.name}</h1><p className="mt-1 text-muted-foreground">{data.session.template?.description}</p></header>{data.questions.map((question: any, index: number) => <Card key={question.id}><CardHeader><CardTitle className="text-base">{index + 1}. {question.question}</CardTitle></CardHeader><CardContent className="space-y-2">{question.options.map((option: any) => <label key={option.id} className="flex min-h-12 cursor-pointer items-center gap-3 rounded-lg border p-3"><input type={question.multiple ? 'checkbox' : 'radio'} name={question.id} checked={(answers[question.id] ?? []).includes(option.id)} onChange={(e) => setAnswers({ ...answers, [question.id]: question.multiple ? e.target.checked ? [...(answers[question.id] ?? []), option.id] : (answers[question.id] ?? []).filter((id) => id !== option.id) : [option.id] })} /><span>{option.label}</span></label>)}</CardContent></Card>)}{error && <p className="rounded bg-red-50 p-3 text-sm text-red-800">{error}</p>}<Button size="lg" className="w-full" disabled={pending || data.questions.some((q: any) => !(answers[q.id]?.length))} onClick={submit}>{pending ? 'Wird abgegeben…' : 'Antworten verbindlich abgeben'}</Button><p className="text-center text-xs text-muted-foreground">Deine Antworten werden erst mit diesem Klick ausgewertet.</p></div>;
}
