'use client';
import { useState, useTransition } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Plus, QrCode, Refrigerator, Snowflake, Warehouse } from 'lucide-react';
import { toastError, toastSuccess } from '@/components/ui/toaster';

type Area={id:string;name:string;location_id:string;location:{name:string}};
type Shelf={id:string;area_id:string;parent_shelf_id:string|null;name:string;place_kind:'unit'|'place';unit_type:string|null;beschreibung:string|null;qr_token:string;last_checked_at:string|null;last_checker:{vorname:string;nachname:string}|null};
type Item={id:string;name:string;shelf_id:string|null;soll_bestand:number|null;min_bestand:number|null;letzte_inventur:number|null};
const icons:Record<string,typeof Warehouse>={kuehlschrank:Refrigerator,gefrierschrank:Snowflake};

export function WarehousePlan({areas,shelves,items}:{areas:Area[];shelves:Shelf[];items:Item[]}) {
 const router=useRouter(); const [pending,start]=useTransition(); const [unitFor,setUnitFor]=useState<string|null>(null);
 function save(fd:FormData, area:Area, kind:'unit'|'place', parentId:string|null){start(async()=>{const res=await fetch('/api/inventory/warehouse',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({intent:'save-place',locationId:area.location_id,areaId:area.id,parentId,kind,name:fd.get('name'),unitType:fd.get('unitType'),description:fd.get('description')})});const body=await res.json();if(!res.ok)return toastError('Speichern fehlgeschlagen',body.error);toastSuccess(kind==='unit'?'Einrichtung angelegt':'Lagerplatz angelegt');setUnitFor(null);router.refresh();});}
 if(!areas.length)return <Card><CardContent className="p-6"><p className="font-medium">Noch kein Lagerraum vorhanden.</p><p className="mt-1 text-sm text-muted-foreground">Lege zuerst unter „Produkte verwalten“ einen Lagerbereich für einen Standort an.</p></CardContent></Card>;
 return <div className="space-y-8">{areas.map(area=>{const units=shelves.filter(s=>s.area_id===area.id&&s.place_kind==='unit');return <section key={area.id} className="space-y-3"><div><h2 className="font-display text-2xl font-bold">{area.name}</h2><p className="text-sm text-muted-foreground">{area.location?.name}</p></div><div className="grid gap-4 lg:grid-cols-2">{units.map(unit=>{const Icon=icons[unit.unit_type??'']??Warehouse;const places=shelves.filter(s=>s.parent_shelf_id===unit.id);return <Card key={unit.id}><CardHeader><CardTitle className="flex items-center gap-2"><Icon className="h-5 w-5"/>{unit.name}<Badge variant="muted">{places.length} Plätze</Badge></CardTitle></CardHeader><CardContent className="space-y-3">{places.length===0&&<p className="text-sm text-muted-foreground">Noch keine Lagerplätze in dieser Einrichtung.</p>}{places.map(place=>{const stock=items.filter(i=>i.shelf_id===place.id);const empty=stock.length===0;const reorder=stock.some(i=>(i.letzte_inventur??0)<(i.min_bestand??0));const due=!place.last_checked_at||Date.now()-new Date(place.last_checked_at).getTime()>30*86400000;return <Link key={place.id} href={`/neo/app/lager/platz/${place.qr_token}`} className="block rounded-xl border p-3 transition hover:border-primary"><div className="flex items-start justify-between gap-2"><div><div className="font-semibold">{place.name}</div><div className="text-xs text-muted-foreground">{stock.length} Produkte</div></div><QrCode className="h-5 w-5"/></div><div className="mt-2 flex flex-wrap gap-1">{empty?<Badge variant="outline">leer</Badge>:<Badge variant="secondary">ok</Badge>}{reorder&&<Badge variant="destructive">nachbestellen</Badge>}{due&&<Badge variant="outline">Inventur fällig</Badge>}</div></Link>})}<Button size="sm" variant="outline" onClick={()=>setUnitFor(unit.id)}><Plus className="h-4 w-4"/> Lagerplatz</Button>{unitFor===unit.id&&<form action={fd=>save(fd,area,'place',unit.id)} className="space-y-2 rounded-lg bg-muted p-3"><Label>Name des Lagerplatzes</Label><Input name="name" required placeholder="Fach A1"/><Input name="description" placeholder="Optionaler Hinweis"/><Button disabled={pending} size="sm">Anlegen</Button></form>}</CardContent></Card>})}</div><form action={fd=>save(fd,area,'unit',null)} className="grid gap-2 rounded-xl border border-dashed p-4 sm:grid-cols-4"><div className="sm:col-span-2"><Label>Neue Einrichtung</Label><Input name="name" required placeholder="Getränkekühlschrank"/></div><div><Label>Art</Label><select name="unitType" className="h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="regal">Regal</option><option value="kuehlschrank">Kühlschrank</option><option value="gefrierschrank">Gefrierschrank</option><option value="schrank">Schrank</option><option value="behaelter">Behälter</option><option value="sonstiges">Sonstiges</option></select></div><Button className="self-end" disabled={pending}><Plus className="h-4 w-4"/> Anlegen</Button></form></section>})}</div>;
}
