'use client';
import * as React from 'react';
import { Copy, Plus, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { toastError, toastSuccess } from '@/components/ui/toaster';

type Slot = { weekday: number; name: string; departmentId?: string | null; position?: string; startTime: string; endTime: string; pauseMinutes: number; headcount: number; sortOrder: number };
type Template = { id: string; name: string; description: string | null; location_id: string; slots: { weekday: number; name: string; department_id: string | null; position: string | null; start_time: string; end_time: string; pause_minutes: number; headcount: number; sort_order: number }[] };
const DAYS = ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'];
const blank = (): Slot => ({ weekday: 0, name: 'Frühschicht', startTime: '08:00', endTime: '16:00', pauseMinutes: 30, headcount: 1, sortOrder: 0 });

export function WeekTemplateManager({ templates, locations, departments }: { templates: Template[]; locations: { id: string; name: string }[]; departments: { id: string; name: string }[] }) {
  const [locationId, setLocationId] = React.useState(locations[0]?.id ?? ''); const [name, setName] = React.useState(''); const [description, setDescription] = React.useState(''); const [slots, setSlots] = React.useState<Slot[]>([blank()]); const [editing, setEditing] = React.useState<string | null>(null); const [busy, setBusy] = React.useState(false);
  function edit(template: Template) { setEditing(template.id); setLocationId(template.location_id); setName(template.name); setDescription(template.description ?? ''); setSlots(template.slots.map(slot => ({ weekday: slot.weekday, name: slot.name, departmentId: slot.department_id, position: slot.position ?? '', startTime: slot.start_time.slice(0, 5), endTime: slot.end_time.slice(0, 5), pauseMinutes: slot.pause_minutes, headcount: slot.headcount, sortOrder: slot.sort_order }))); }
  async function action(action: string, templateId?: string) { setBusy(true); const response = await fetch('/api/scheduling/planner', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, locationId, templateId, name, description, slots }) }); const result = await response.json().catch(() => null); setBusy(false); if (!response.ok) return toastError('Vorlage konnte nicht gespeichert werden', result?.error); toastSuccess(action === 'deleteTemplate' ? 'Vorlage gelöscht' : action === 'copyTemplate' ? 'Vorlage kopiert' : 'Wochenvorlage gespeichert'); window.location.reload(); }
  return <div className="grid gap-4 xl:grid-cols-[1fr_1.4fr]"><Card className="p-4"><h2 className="font-semibold">Wochenvorlagen</h2><div className="mt-3 space-y-2">{templates.map(template => <div key={template.id} className="flex items-center gap-2 rounded-lg border p-3"><button className="min-w-0 flex-1 text-left" onClick={() => edit(template)}><strong className="block truncate text-sm">{template.name}</strong><span className="text-xs text-muted-foreground">{locations.find(location => location.id === template.location_id)?.name ?? 'Standort'} · {template.slots.length} Bedarfszeiten</span></button><Button size="sm" variant="ghost" aria-label="Kopieren" onClick={() => { setLocationId(template.location_id); void action('copyTemplate', template.id); }}><Copy className="h-4 w-4" /></Button><Button size="sm" variant="ghost" aria-label="Löschen" onClick={() => { if (confirm('Wochenvorlage wirklich löschen?')) { setLocationId(template.location_id); void action('deleteTemplate', template.id); } }}><Trash2 className="h-4 w-4" /></Button></div>)}{!templates.length && <p className="text-sm text-muted-foreground">Noch keine vollständige Wochenvorlage.</p>}</div></Card>
  <Card className="p-4"><h2 className="font-semibold">{editing ? 'Wochenvorlage bearbeiten' : 'Neue Wochenvorlage'}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-xs">Name<input className="h-9 rounded-md border px-2" value={name} onChange={e => setName(e.target.value)} /></label><label className="grid gap-1 text-xs">Standort<select className="h-9 rounded-md border px-2" value={locationId} onChange={e => setLocationId(e.target.value)}>{locations.map(location => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label><label className="grid gap-1 text-xs sm:col-span-2">Beschreibung<input className="h-9 rounded-md border px-2" value={description} onChange={e => setDescription(e.target.value)} /></label></div>
  <div className="mt-4 space-y-3">{slots.map((slot, index) => <div key={index} className="grid gap-2 rounded-lg border p-3 sm:grid-cols-4"><select aria-label="Wochentag" value={slot.weekday} onChange={e => update(index, { weekday: Number(e.target.value) })} className="h-9 rounded-md border px-2 text-sm">{DAYS.map((day, dayIndex) => <option key={day} value={dayIndex}>{day}</option>)}</select><input aria-label="Schichtname" className="h-9 rounded-md border px-2 text-sm" value={slot.name} onChange={e => update(index, { name: e.target.value })}/><input aria-label="Position" placeholder="Position" className="h-9 rounded-md border px-2 text-sm" value={slot.position ?? ''} onChange={e => update(index, { position: e.target.value })}/><select aria-label="Bereich" className="h-9 rounded-md border px-2 text-sm" value={slot.departmentId ?? ''} onChange={e => update(index, { departmentId: e.target.value || null })}><option value="">Alle Bereiche</option>{departments.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select><input aria-label="Start" type="time" className="h-9 rounded-md border px-2" value={slot.startTime} onChange={e => update(index, { startTime: e.target.value })}/><input aria-label="Ende" type="time" className="h-9 rounded-md border px-2" value={slot.endTime} onChange={e => update(index, { endTime: e.target.value })}/><label className="text-xs">Pause<input type="number" className="mt-1 h-9 w-full rounded-md border px-2" value={slot.pauseMinutes} onChange={e => update(index, { pauseMinutes: Number(e.target.value) })}/></label><label className="text-xs">Benötigte Personen<input type="number" min="1" className="mt-1 h-9 w-full rounded-md border px-2" value={slot.headcount} onChange={e => update(index, { headcount: Number(e.target.value) })}/></label></div>)}</div>
  <div className="mt-3 flex flex-wrap gap-2"><Button variant="outline" onClick={() => setSlots(current => [...current, { ...blank(), sortOrder: current.length }])}><Plus className="h-4 w-4"/> Bedarfszeit</Button><Button disabled={busy || !name || !locationId} onClick={() => action(editing ? 'updateTemplate' : 'createTemplate', editing ?? undefined)}>Speichern</Button>{editing && <Button variant="ghost" onClick={() => { setEditing(null); setName(''); setDescription(''); setSlots([blank()]); }}>Neue Vorlage</Button>}</div></Card></div>;
  function update(index: number, value: Partial<Slot>) { setSlots(current => current.map((slot, slotIndex) => slotIndex === index ? { ...slot, ...value } : slot)); }
}
